// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PlaywrightReqnroll.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Login")]
    public partial class LoginFeature
    {
        
        private Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "Login.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Login", "This feature tests the login and checkout functionalty for sausedemo application", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Login to sausedemo application")]
        [NUnit.Framework.CategoryAttribute("UI")]
        [NUnit.Framework.CategoryAttribute("ValidateItemPice")]
        public async System.Threading.Tasks.Task LoginToSausedemoApplication()
        {
            string[] tagsOfScenario = new string[] {
                    "UI",
                    "ValidateItemPice"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Login to sausedemo application", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("Launch the url", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.WhenAsync("Enter valid username and password", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
 await testRunner.AndAsync("Click on Login button", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
 await testRunner.ThenAsync("Validate page title as inventory", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
 await testRunner.WhenAsync("Select any item from list of products displayed", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
 await testRunner.ThenAsync("Validate price is dispalyed same as products page", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
 await testRunner.WhenAsync("Click on Add to cart button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
 await testRunner.AndAsync("Click on cart image", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.ThenAsync("Navigate to cart page and verify same price is displayed or not", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
 await testRunner.WhenAsync("click on checkout button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
 await testRunner.ThenAsync("Provide firstname as ramya", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 18
 await testRunner.AndAsync("Provide lastname as thondapu", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync("Provide zipcode as 502032", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.WhenAsync("Click on continue button", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
 await testRunner.ThenAsync("Validate item price is displayed same as checkout page", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
 await testRunner.AndAsync("Click on Finish button", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
